version: '3.2'

services:

  flask_app:
    build:
      context: ..
      dockerfile: Docker/flask_app.df
    image: flask_app:latest
    logging:
      driver: syslog
      options:
        syslog-address: "udp://0.0.0.0:5514"
        mode: non-blocking
        max-buffer-size: 10m
        tag: "{{.Name}}"
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - PYTHONPATH=.
      - CH_HOST=172.17.0.1
      - KAGGLE_KEY=$KK
      - KAGGLE_USERNAME=$KU
    ports:
      - "3039:3039"
    container_name: flask_app
    networks:
      - hobs

  grafana:
    build:
      context: ..
      dockerfile: Docker/grafana.df
      args:
        GUAI: $GUAI
        GTMI: $GTMI
    image: grafana:v6.6.2
    logging:
      driver: syslog
      options:
        syslog-address: "udp://0.0.0.0:5514"
        mode: non-blocking
        max-buffer-size: 10m
        tag: "{{.Name}}"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "3456:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    container_name: grafana
    networks:
      - hobs

  clickhouse:
    image: yandex/clickhouse-server
    logging:
      driver: syslog
      options:
        syslog-address: "udp://0.0.0.0:5514"
        mode: non-blocking
        max-buffer-size: 10m
        tag: "{{.Name}}"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-storage:/var/lib/clickhouse
    container_name: clickhouse.db.server
    networks:
      - hobs

  jenkins:
    image: datasights/jenkins:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
      - "50000:50000"
    privileged: true
    user: root
    container_name: jenkinsapp
    volumes:
      - jenkins-store:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hobs

  rsyslog:
    image: voxxit/rsyslog
    ports:
      - "5514:514/udp"
    volumes:
      - /tmp/clog:/var/log
    container_name: rsyslog.service
    networks:
      - hobs

networks:
  hobs:

volumes:
  jenkins-store:
  grafana-storage:
  clickhouse-storage:
